spring:
  data:
    mongodb:
      uri: mongodb+srv://alan:alan@springauthentication.e1194nk.mongodb.net/SpringAuthentication?retryWrites=true&w=majority
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true